### ISSUE TITLE
Get rid of internal "value" state

### ISSUE THREAD

**Issue by narqo** [narqo/react-islands#63]
It feels weird that `Checkbox`, `Radio` and other components have an internal `checked` and `value` states that are synchronised with props and the DOM attribute. The standard approach for React is to make components stateless if possible.

We can think if we can get rid of `checked` and `value` synchronisation. ~~Components could work as "controlled" if both `checked` and `onChange` props passed and as "uncontrolled" if only `checked` presents.~~
- [x] Checkbox
- [x] CheckboxGroup
- [x] Radio
- [x] RadioGroup
- [x] TextInput
- [x] TextArea

**Comment by vodkabears** [comment]
+

> Components could work as "controlled" if both checked and onChange props passed and as "uncontrolled" if only checked presents.

That's wrong.

Example of controlled:

```
onChange(checked) {
  ...
  this.setState({ isChecked: checked });
}

render() {
   return <Checkbox checked={this.state.isChecked} onChange={this.onChange} />;
}
```

Example of controlled that should be uncontrolled:

```
onChange(checked) {
  console.log(checked);
}

render() {
  return <Checkbox checked={true} onChange={this.onChange} />;
}
```

**Comment by narqo** [comment]
Agreed. It feels more challenging than it looks from the first sign. 

For example, it's not clear how to make a fully uncontrolled `Checkbox`, that still set it's CSS classes (e.g. `_checked`) properly.
